version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-stock
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Stock
      MYSQL_USER: stock
      MYSQL_PASSWORD: stock@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - stock-network
      -
  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana:7.4.1
    container_name: grafana
    ports:
      - 3000:3000

volumes:
  mysql-data:
    driver: local

networks:
  stock-network:
    driver: bridge

