version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-stock
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Stock
      MYSQL_USER: stock
      MYSQL_PASSWORD: stock@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - stock-network

volumes:
  mysql-data:
    driver: local

networks:
  stock-network:
    driver: bridge
