spring:
  application:
  name: stock
  cache:
    type: redis
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

